name: Apple
on:
  workflow_dispatch:
jobs:
  build:
    name: ${{matrix.NAME}}
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        include:
          - NAME: iOS
            PLATFORM: ios
            FRAMEWORK: ios
            PROFILE: NitaqPos
          - NAME: MacOS
            PLATFORM: macos
            FRAMEWORK: maccatalyst
            PROFILE: NitaqPosMac
    env:
      ALSULTAN_APP_TITLE: 'Nitaq'
      ALSULTAN_APP_PACKAGE: 'alsultan.pos'

    steps:
    
    - name: Source
      run: |
        curl -Lks "${{secrets.ALSULTAN_API_SERVICE}}&Service=StageSource&Project=MAUI-${{matrix.PLATFORM}}&AppTitle=${{env.ALSULTAN_APP_TITLE}}&AppPackage=${{env.ALSULTAN_APP_PACKAGE}}&CodeSignProfile=${{matrix.PROFILE}}" > Z
        unzip -qq Z || true
        chmod -R 777 Common/Vendors/GitHub/Actions
    
    - name: DotNet
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/InstallDotNet.sh ${{matrix.FRAMEWORK}} ${{github.workspace}}/DotNet
    
    - name: Security
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/AppleCertificates.sh ${{matrix.PLATFORM}} ${{matrix.PROFILE}}

    - name: Build
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/BuildMaui.sh ${{matrix.FRAMEWORK}} ${{github.workspace}}/DotNet

    - name: Publish
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/PublishMauiApple.sh ${{matrix.PLATFORM}}

            
