name: Apple Builder
on:
  workflow_dispatch:
jobs:
  Build:
    name: ${{matrix.NAME}}
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        include:
          - NAME: iOS
            PLATFORM: ios
            FRAMEWORK: ios
            PROFILE: NitaqPos
          - NAME: MacOS
            PLATFORM: macos
            FRAMEWORK: maccatalyst
            PROFILE: NitaqPosMac
    env:
      ALSULTAN_APP_TITLE: 'Nitaq'
      ALSULTAN_APP_PACKAGE: 'alsultan.pos'

    steps:
    
    - name: Source
      run: |
        for i in {1..20}; do
            echo "Downloading Source Attempt ${i}..."
            test $i != 1 && sleep 30
            curl -Lk -A 'ALSULTAN' "${{secrets.ALSULTAN_API_SERVICE}}&OP=MauiGetSource&Platform=${{matrix.PLATFORM}}&AppTitle=${{env.ALSULTAN_APP_TITLE}}&AppPackage=${{env.ALSULTAN_APP_PACKAGE}}&SignProfile=${{matrix.PROFILE}}" -o Z || continue
            unzip -q Z && break || continue
        done
        chmod -R 777 Common/Vendors/GitHub/Actions        
    
    - name: DotNet
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/InstallDotNet.sh ${{matrix.FRAMEWORK}} ${{github.workspace}}/DotNet
    
    - name: Security
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/AppleCertificates.sh ${{matrix.PLATFORM}} ${{matrix.PROFILE}}

    - name: Build
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/BuildMaui.sh ${{matrix.FRAMEWORK}} ${{github.workspace}}/DotNet

    - name: Publish
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/PublishMauiApple.sh ${{matrix.PLATFORM}}

            
