name: Apple
on:
  workflow_dispatch:
jobs:
  build:
    name: ${{matrix.NAME}}
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        include:        
          - NAME: iOS
            PLATFORM: ios
            FRAMEWORK: ios
            PROFILE: NitaqPos
          - NAME: MacOS
            PLATFORM: macos
            FRAMEWORK: maccatalyst
            PROFILE: NitaqPosMac
    env:
      ALSULTAN_API: ${{secrets.ALSULTAN_API}}
      ALSULTAN_APP_TITLE: 'Nitaq'
      ALSULTAN_APP_PACKAGE: 'alsultan.pos'
      ALSULTAN_DOTNET_DIR: ${{github.workspace}}/DotNet

    steps:
    
    - name: Source       
      run: |
        curl -Lks "https://alsultan.vip/Service/Vendors/GitHub/Services?API=${{env.ALSULTAN_API}}&Service=StageSource&Project=MAUI-${{matrix.PLATFORM}}&AppTitle=${{env.ALSULTAN_APP_TITLE}}&AppPackage=${{env.ALSULTAN_APP_PACKAGE}}&CodeSignProfile=${{matrix.PROFILE}}" > src.zip
        unzip -qq src.zip || true
        rm src.zip
        chmod -R 777 ALSULTAN/Common/Vendors/GitHub/Actions
    
    - name: DotNet
      run: ${{github.workspace}}/ALSULTAN/Common/Vendors/GitHub/Actions/InstallDotNet.sh ${{matrix.FRAMEWORK}} ${{env.ALSULTAN_DOTNET_DIR}}
    
    - name: Security
      run: ${{github.workspace}}/ALSULTAN/Common/Vendors/GitHub/Actions/AppleCertificates.sh ${{matrix.PLATFORM}} ${{matrix.PROFILE}}

    - name: Build
      run: ${{github.workspace}}/ALSULTAN/Common/Vendors/GitHub/Actions/BuildMaui.sh ${{matrix.FRAMEWORK}} ${{env.ALSULTAN_DOTNET_DIR}}

    - name: Publish
      run: ${{github.workspace}}/ALSULTAN/Common/Vendors/GitHub/Actions/PublishMauiApple.sh ${{matrix.PLATFORM}}

            
