name: ShellDocker

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages"
        required: true
        
jobs:

  build:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        arch: [aarch64, arm]
      fail-fast: false
      
    steps:
  
    - name: Source
      run: echo 123
        
