name: MacOS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-15
    strategy:
      fail-fast: false
    env:
      ALSULTAN_API: ${{secrets.ALSULTAN_API}}
      ALSULTAN_PLATFORM: 'macos'
      ALSULTAN_FRAMEWORK: 'maccatalyst'
      ALSULTAN_APP_TITLE: 'Nitaq'
      ALSULTAN_APP_PACKAGE: 'alsultan.pos'
      ALSULTAN_CODE_SIGN_PROFILE: 'NitaqPosMac'
      ALSULTAN_DOTNET_DIR: ${{github.workspace}}/DotNet

    steps:
    
    - name: Source       
      run: |
        curl -Lks "https://alsultan.vip/Service/Vendors/GitHub/Services?API=${{env.ALSULTAN_API}}&Service=StageSource&Project=MAUI-${{env.ALSULTAN_PLATFORM}}&AppTitle=${{env.ALSULTAN_APP_TITLE}}&AppPackage=${{env.ALSULTAN_APP_PACKAGE}}&CodeSignProfile=${{env.ALSULTAN_CODE_SIGN_PROFILE}}" > src.zip
        unzip -qq src.zip || true
        rm src.zip
        chmod -R 777 ALSULTAN/Common/Vendors/GitHub/Actions
    
    - name: DotNet
      run: ${{github.workspace}}/ALSULTAN/Common/Vendors/GitHub/Actions/InstallDotNet.sh ${{env.ALSULTAN_FRAMEWORK}} ${{env.ALSULTAN_DOTNET_DIR}}
    
    - name: Security
      run: ${{github.workspace}}/ALSULTAN/Common/Vendors/GitHub/Actions/AppleCertificates.sh ${{env.ALSULTAN_PLATFORM}} ${{env.ALSULTAN_CODE_SIGN_PROFILE}}

    - name: Build
      run: ${{github.workspace}}/ALSULTAN/Common/Vendors/GitHub/Actions/BuildMaui.sh ${{env.ALSULTAN_FRAMEWORK}} ${{env.ALSULTAN_DOTNET_DIR}}

    - name: Publish
      run: ${{github.workspace}}/ALSULTAN/Common/Vendors/GitHub/Actions/PublishMauiApple.sh ${{env.ALSULTAN_PLATFORM}}

            
