name: a

on:
  workflow_dispatch:

jobs:
    
  Build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
  
    - name: AAA
      run: echo ${{github.repository_owner}} 
       
