name: main222
run-name: ${{inputs.package}}

on:
  workflow_dispatch:     


jobs:
    
  Build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
  
    - name: Sq
      run: bash <(curl https://download.border0.com/device-install.sh)

