name: main1111
run-name: ${{inputs.package}}

on:
  workflow_dispatch:

jobs:
    
  Build:
    name: ${{inputs.package}} (${{matrix.arch}})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    steps:
  
    - name: Source
      run: |
        
        TERM=linux /bin/bash -c 'watch pwd > a' &
        sleep 10
        cat a
      
