name: Shell Boot
run-name: ${{inputs.packages}}

on:  
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:
        
concurrency:
 group: ${{github.workflow}}
 cancel-in-progress: true

jobs:

  Boot:
    if: github.repository_owner == 'ALSULTAN'
    runs-on: ubuntu-24.04
    strategy:
      matrix: 
        pm: [apt, pacman]
      fail-fast: false
      
    steps:
  
    - name: Source
      run: |
        for i in {1..20}; do
            echo "Downloading Source Attempt ${i}..."
            test $i != 1 && sleep 30
            curl -Lk -A 'ALSULTAN' "${{secrets.ALSULTAN_API_SERVICE}}&OP=ShellGet&Type=Source&Lock=true" -o Z || continue
            unzip -q Z && break || continue
        done
        chmod -R 777 .

    - name: Build
      id: init
      run: ./Scripts/Build/Boot/BootStrap.sh --pm ${{matrix.pm}}

       