name: ShellDocker
run-name: ${{inputs.package}}

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package"
        required: true
        
jobs:
 
  Build_X86:
    name: ${{inputs.package}} (${{matrix.arch}})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [i686]
      fail-fast: false
    env:
      ALSULTAN_API: ${{secrets.ALSULTAN_API}}

    steps:
  
    - name: Source
      run: |
        # Downloading Shell Sources
        true
       
    - name: Docker
      run: |
        true
        
    - name: Build
      id: build
      run: |
        # Building Shell Package
        echo "skip-upload=true" >> $GITHUB_OUTPUT

    - name: Upload
      if: ${{steps.build.outputs.skip-upload != 'true' }}
      run: |
         echo ${{steps.build.outputs.skip-upload}}
