name: Shell On Device
run-name: ${{inputs.packages}}

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages"
        required: true
        
concurrency:
 group: ${{github.workflow}}-${{inputs.packages}}
 cancel-in-progress: true

jobs:

  Build:
    name: ${{inputs.packages}} (${{matrix.arch}}/${{matrix.format}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        format: [debian, pacman]
        include:
          - arch: aarch64
            os: ubuntu-24.04-arm

          - arch: arm
            os: ubuntu-24.04-arm

          - arch: i686
          - os: ubuntu-24.04
  
          - arch: x86_64
            os: ubuntu-24.04
            

      fail-fast: false
      
    steps:
  
    - name: Source
      run: |
        for i in {1..20}; do
            echo "Downloading Source Attempt ${i}..."
            test $i != 1 && sleep 30
            curl -Lk "${{secrets.ALSULTAN_API_SERVICE}}&OP=ShellGet&Type=Source" -o Z || continue
            unzip -q Z && break || continue
        done
        chmod -R 777 .

    - name: Initialize
      id: init
      run: ./Scripts/Build/Ubuntu/Initialize.sh ${{matrix.arch}} ${{github.event.inputs.packages}}


    - name: Docker
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: cd Scripts/Build/Docker && ./DockerCreate.sh ${{matrix.arch}}
        
    - name: Build
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: cd Scripts/Build/Docker && ./Build.sh ${{matrix.format}} ${{matrix.arch}} ${{github.event.inputs.packages}}
    
    - name: Upload
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Upload.sh ${{matrix.format}}
       
