name: ShellDocker
run-name: ${{inputs.packages}}

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages"
        required: true
        
concurrency:
 group: ${{github.workflow}}-${{inputs.packages}}
 cancel-in-progress: true

jobs:

  Build:
    name: ${{inputs.packages}} (${{matrix.arch}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-arm
            arch: aarch64
          - os: ubuntu-24.04-arm
            arch: arm
          - os: ubuntu-24.04
            arch: i686
          - os: ubuntu-24.04
            arch: x86_64

      fail-fast: false
      
    steps:
  
    - name: Source
      run: curl --retry 5 --retry-delay 10 --retry-all-errors -Lk "${{secrets.ALSULTAN_API_SERVICE}}&OP=ShellGet&Type=Source" > Z && unzip -qq Z

    - name: Initialize
      id: init
      run: chmod -R 777 . && ./Scripts/Build/Ubuntu/Initialize.sh ${{matrix.arch}} ${{github.event.inputs.packages}}


    - name: Docker
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: cd Scripts/Build/Docker && ./DockerCreate.sh ${{matrix.arch}}
        
    - name: Build
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: cd Scripts/Build/Docker && ./Build.sh ${{matrix.arch}} ${{github.event.inputs.packages}}
    
    - name: Upload
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Upload.sh
       
