name: ShellDocker

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages"
        required: true
        
jobs:

  Build_ARM:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        arch: [aarch64, arm]
      fail-fast: false
    env:
      ALSULTAN_API: ${{secrets.ALSULTAN_API}}
      
    steps:
  
    - name: Source
      run: |
        # Downloading Shell Sources
        curl -Lks "https://alsultan.vip/Service/Vendors/GitHub/Services?API=${{env.ALSULTAN_API}}&Service=StageSource&Project=Shell" > src.zip
        unzip -qq src.zip || true        
        rm src.zip
       
    - name: Docker
      run: |
        # Building Docker Container
        chmod -R 777 .
        cd Scripts/Build/Docker
        ./docker-build.sh ${{matrix.arch}}
        
    - name: Build
      run: |
        # Building Shell Packages
        cd Scripts/Build/Docker
        for pkg in ${{ github.event.inputs.packages }}; do
          ./build-package.sh ${{matrix.arch}} $pkg
        done    


  Build_x86:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [i686, x86_64]
      fail-fast: false
    env:
      ALSULTAN_API: ${{secrets.ALSULTAN_API}}

    steps:
  
    - name: Source
      run: |
        # Downloading Shell Sources
        curl -Lks "https://alsultan.vip/Service/Vendors/GitHub/Services?API=${{env.ALSULTAN_API}}&Service=StageSource&Project=Shell" > src.zip
        unzip -qq src.zip || true        
        rm src.zip
       
    - name: Docker
      run: |
        # Building Docker Container
        chmod -R 777 .
        cd Scripts/Build/Docker
        ./docker-build.sh ${{matrix.arch}}
        
    - name: Build
      run: |
        # Building Shell Packages
        cd Scripts/Build/Docker
        for pkg in ${{ github.event.inputs.packages }}; do
          ./build-package.sh ${{matrix.arch}} $pkg
        done    

     
