name: Shell
run-name: ${{inputs.package}}

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package"
        required: true
        
concurrency:
 group: ${{github.workflow}}-${{inputs.package}}
 cancel-in-progress: true

jobs:
    
  Build:
    name: ${{inputs.package}} (${{matrix.arch}})
    runs-on: ubuntu-24.04
    strategy:
      matrix: 
        arch: [aarch64, arm, i686, x86_64]
      fail-fast: false

    steps:
  
    - name: Source
      run: curl -Lks "${{secrets.ALSULTAN_API_SERVICE}}&Service=StageSource&Project=Shell" > Z && unzip -qq Z

    - name: Initialize
      id: init
      run: chmod -R 777 . && ./Scripts/Build/Ubuntu/Initialize.sh ${{matrix.arch}} ${{github.event.inputs.package}}

    - name: Clean
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Clean.sh
        
    - name: Prepare
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/SetUp.sh
        
    - name: Build
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Build.sh ${{matrix.arch}} ${{github.event.inputs.package}}

    - name: Upload
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Upload.sh ${{secrets.ALSULTAN_API_SERVICE}}

