name: ShellBlacked

on:
  workflow_dispatch:
        
concurrency:
 group: ShellBlacked
 cancel-in-progress: true

jobs:
    
  Build:
    name: Blacked (${{matrix.arch}})  
    runs-on: ubuntu-24.04
    strategy:
      matrix: 
        arch: [aarch64, arm, i686, x86_64]
      fail-fast: false

    steps:
  
    - name: Source
      run: curl -Lks "${{secrets.ALSULTAN_API_SERVICE}}&OP=ShellGet&Type=Source" > Z && unzip -qq Z

    - name: Initialize
      id: init
      run: chmod -R 777 .

    - name: Clean
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Clean.sh
        
    - name: Prepare
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/SetUp.sh
        
    - name: Build
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Blacked.sh ${{matrix.arch}}

    - name: Upload
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Upload.sh

