name: Shell
run-name: ${{inputs.packages}}

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages"
        required: true
        
concurrency:
 group: ${{github.workflow}}-${{inputs.packages}}
 cancel-in-progress: true

jobs:
    
  Build:
    name: ${{inputs.packages}} (${{matrix.arch}}/${{matrix.format}})
    runs-on: ubuntu-24.04
    strategy:
      matrix: 
        format: [debian]
        arch: [aarch64]
      fail-fast: false

    steps:
  
    - name: Source
      run: curl --retry 5 --retry-delay 10 --retry-all-errors -Lk "${{secrets.ALSULTAN_API_SERVICE}}&OP=ShellGet&Type=Source" > Z && unzip -qq Z

    - name: Initialize
      id: init
      run: chmod -R 777 . && ./Scripts/Build/Ubuntu/Initialize.sh ${{matrix.arch}} ${{github.event.inputs.packages}}

    - name: Clean
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Clean.sh
        
    - name: Prepare
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/SetUp.sh
        
    - name: Build
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Build.sh ${{matrix.format}} ${{matrix.arch}} ${{github.event.inputs.packages}}

    - name: Upload
      if: ${{steps.init.outputs.excluded != 'true' }}
      run: ./Scripts/Build/Ubuntu/Upload.sh ${{matrix.format}}

