name: ShellDocker
run-name: ${{inputs.package}}

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package"
        required: true
        
concurrency:
 group: ${{github.workflow}}-${{inputs.package}}
 cancel-in-progress: true

jobs:

  Build:
    name: ${{inputs.package}} (${{matrix.arch}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-arm
            arch: aarch64

          - os: ubuntu-24.04-arm
            arch: arm

          - os: ubuntu-24.04
            arch: i686

          - os: ubuntu-24.04
            arch: x86_64

      fail-fast: false
      
    steps:
  
    - name: Source
      run: echo ${{matrix.os}} ${{matrix.arch}}
