name: SQLCipher
on:
  workflow_dispatch:
jobs:
  SQLCipher:
    runs-on: windows-2025
    strategy:
      fail-fast: false

    steps:  
    - name: Source
      run: curl -Lks "${{secrets.ALSULTAN_API_SERVICE}}&Service=StageSource&Project=Shell" > Z && unzip -qq Z

    - name: Build
      shell: cmd
      run: |
        dir
        cd Packages\sqlcipher\Custom\Windows
        Build.cmd
