name: SQLCipher
on:
  workflow_dispatch:
jobs:
  SQLCipher:
    runs-on: windows-2025
    strategy:
      fail-fast: false

    steps:  
    - name: Source
      run: curl -Lks "${{secrets.ALSULTAN_API_SERVICE}}&OP=ShellGet&Type=Source" > Z && unzip -qq Z

    - name: Build
      shell: cmd
      run: cd Packages\sqlcipher\Custom\Windows & Build.cmd
