name: Test1
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
  
    - name: S1
      run: |
          df -h  
          sudo rm -rf /opt/ghc /opt/hostedtoolcache /usr/share/dotnet /usr/share/swift
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/.ghcup/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/lib/android
          
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
          sudo rm -rf /home/runner/.cargo
          sudo rm -rf /home/runner/.rustup
          sudo rm -rf /usr/local/julia*
          sudo rm -rf /opt/microsoft
          sudo rm -rf /usr/lib/dotnet
          
          sudo swapoff -a
          sudo fallocate -l 16G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

          df -h  
