name: Test
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
  
    - name: S1
      run: |
        df -h
        du -sh /usr/local/* /opt/* /usr/* | sort -hr
        
