name: Test1
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
  
    - name: S1
      run: |
          df -h  
                       
          # Just Removing Folders (Faster)
          
          echo 'Moving Trash Folders To Temp'
          
          TMP_FOLDER=/tmp/put_here_to_remove/
          
          sudo mkdir -p $TMP_FOLDER
          
          sudo mv -v /opt/ghc  						      $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /opt/hostedtoolcache                   $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/share/dotnet                      $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/share/swift                       $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/local/graalvm/                    $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/local/.ghcup/                     $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/local/share/powershell            $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/local/share/chromium              $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/local/lib/node_modules            $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/local/lib/android                 $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/local/share/boost                 $TMP_FOLDER 2>/dev/null || true
          sudo mv -v "$AGENT_TOOLSDIRECTORY"                $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /home/runner/.cargo                    $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /home/runner/.rustup                   $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/local/julia*                      $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /opt/microsoft                         $TMP_FOLDER 2>/dev/null || true
          sudo mv -v /usr/lib/dotnet                        $TMP_FOLDER 2>/dev/null || true
          
          echo 'Making Swap File Of 16GB'
          sudo swapoff -a
          sudo fallocate -l 16G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          
          echo 'Temp Folder Will Be Removed In Background'
          sudo rm -rf $TMP_FOLDER > /dev/null 2>&1 &

          df -h  
