name: Test1
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
  
    - name: S1
      run: |
          df -h  
            
                 # Just Removing Folders (Faster)
                 
                 sudo rm -rfv /opt/ghc /opt/hostedtoolcache /usr/share/dotnet /usr/share/swift
                 sudo rm -rfv /usr/local/graalvm/
                 sudo rm -rfv /usr/local/.ghcup/
                 sudo rm -rfv /usr/local/share/powershell
                 sudo rm -rfv /usr/local/share/chromium
                 sudo rm -rfv /usr/local/lib/node_modules
                 sudo rm -rfv /usr/local/lib/android

                 sudo rm -rfv /usr/local/share/boost
                 sudo rm -rfv "$AGENT_TOOLSDIRECTORY"

                 sudo rm -rfv /home/runner/.cargo
                 sudo rm -rfv /home/runner/.rustup
                 sudo rm -rfv /usr/local/julia*
                 sudo rm -rfv /opt/microsoft
                 sudo rm -rfv /usr/lib/dotnet

                 sudo swapoff -a
                 sudo fallocate -l 16G /swapfile
                 sudo chmod 600 /swapfile
                 sudo mkswap /swapfile
                 sudo swapon /swapfile

          df -h  
