name: Test1
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
  
    - name: S1
      run: |
          echo '1==================';df -h /tmp || true
          echo '2==================';df -h ${{github.workspace}} || true
          echo '3==================';df -h ~ || true
          echo '4==================';df -h / || true
