name: Test1
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
   
    - name: S1
      run: |
       echo -e "\n\n\nRemoving Large System Packages (Free `df -h . | tail -1 | awk '{print $4}'`)\n"
       sudo apt-get -yq purge $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(mecab|azure|aspnetcore|liblldb-|netstandard|clang|gfortran|mysql|google|postgresql|cabal|dotnet|ghc|mongodb|libmono|llvm|kubectl|podman|ruby3|mercurial|git-lfs|skopeo|buildah|vim|nano|python3-botocore|powershell|shellcheck|firefox|microsoft-edge|temurin-21-jdk|temurin-11-jdk|temurin-8-jdk|snapd)') || true
       
       echo -e "\n\n\nRemoving Docker Containers (Free `df -h . | tail -1 | awk '{print $4}'`)\n"
       sudo docker image prune --all --force
       sudo docker builder prune -a
       sudo apt-get -yqq purge containerd.io
       
       echo -e "\n\n\nCleaning Up System Packages (Free `df -h . | tail -1 | awk '{print $4}'`)\n"
       sudo apt-get -yqq autoremove
       sudo apt-get -yqq clean
       
       
       echo -e "\n\n\nMoving Trash Folders To Temp (Free `df -h . | tail -1 | awk '{print $4}'`)\n"
       TMP_FOLDER=/tmp/put_here_to_remove/
       
       sudo mkdir -p $TMP_FOLDER
       
       sudo mv -v /opt/ghc  						     $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /opt/hostedtoolcache                   $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/share/dotnet                      $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/share/swift                       $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/local/graalvm/                    $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/local/.ghcup/                     $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/local/share/powershell            $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/local/share/chromium              $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/local/lib/node_modules            $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/local/lib/android                 $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/local/share/boost                 $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /home/runner/.cargo                    $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /home/runner/.rustup                   $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/local/julia*                      $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /opt/microsoft                         $TMP_FOLDER 2>/dev/null || true
       sudo mv -v /usr/lib/dotnet                        $TMP_FOLDER 2>/dev/null || true
       sudo mv -v "$AGENT_TOOLSDIRECTORY"                $TMP_FOLDER 2>/dev/null || true
       
       echo -e "\n\n\nMaking 12G Swap File (Free `df -h . | tail -1 | awk '{print $4}'`)\n"
       sudo swapoff -a
       sudo fallocate -l 12G /swapfile
       sudo chmod 600 /swapfile
       sudo mkswap /swapfile
       sudo swapon /swapfile
       
       echo -e "\n\n\nTemp Folder Will Be Removed (Free `df -h . | tail -1 | awk '{print $4}'`)\n"
       sudo rm -rf $TMP_FOLDER > /dev/null 2>&1 &

       dpkg-query -Wf '${Installed-Size}K\t${Package}\n' | sort -nr | head -10 | numfmt --from=auto --to=si

    - name: S2
      run: |
        for i in $(seq 1 500);
        do
            ls -la /tmp/put_here_to_remove/ || true
            df -h . | tail -1 | awk '{print $4}' 
            sleep 2
        done


