name: Test
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
  
    - name: S1
      run: |
        du -sh ~/.cargo || true
        du -sh ./target || true
        du -sh ~/.rustup || true

