name: Test1
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
  
    - name: S1
      run: |
          dotnet --info
          exit 1
          df -h
          sudo apt purge -yq $(
                     		dpkg -l |
                     			grep '^ii' |
                     			awk '{ print $2 }' |
                     			grep -P '(mecab|linux-azure-tools-|aspnetcore|liblldb-|netstandard-|clang-tidy|clang-format|gfortran-|mysql-|google-cloud-cli|postgresql-|cabal-|dotnet-|ghc-|mongodb-|libmono|llvm-16|llvm-17)'
                     	) || true
                     
                     	sudo apt purge -yq \
                     		snapd \
                     		kubectl \
                     		podman \
                     		ruby3.2-doc \
                     		mercurial-common \
                     		git-lfs \
                     		skopeo \
                     		buildah \
                     		vim \
                     		python3-botocore \
                     		azure-cli \
                     		powershell \
                     		shellcheck \
                     		firefox \
                     		google-chrome-stable \
                     		microsoft-edge-stable \
                     		google-cloud-cli \
                     		temurin* \
                     		libllvm* \
                     		llvm* \
                     		dotnet* \
                     		google-cloud-cli-anthoscli \
                     		mysql* \
                     		linux-azure* \
                     		gcc* || true
                     
                     		
                     	# Directories
                     	sudo rm -fr /opt/ghc /opt/hostedtoolcache /usr/share/dotnet /usr/share/swift
                     	sudo rm -rf /usr/local/graalvm/
                     	sudo rm -rf /usr/local/.ghcup/
                     	sudo rm -rf /usr/local/share/powershell
                     	sudo rm -rf /usr/local/share/chromium
                     	sudo rm -rf /usr/local/lib/node_modules
                     	sudo rm -rf /usr/local/lib/android
                     
                     	# https://github.com/actions/runner-images/issues/709#issuecomment-612569242
                     	sudo rm -rf "/usr/local/share/boost"
                     	sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                     
                     	# We shouldn't remove docker & it's images when running from `package_updates` workflow.
                     	if [ "${CLEAN_DOCKER_IMAGES-true}" = "true" ]; then
                     		sudo docker image prune --all --force
                     		sudo docker builder prune -a
                     		sudo apt purge -yq containerd.io
                     	fi
                     
                     	sudo rm -rf /home/runner/.cargo
                     	sudo rm -rf /home/runner/.rustup
                     	sudo rm -rf /usr/local/julia*
                     	sudo rm -rf /opt/microsoft
                     
                     	sudo apt autoremove -yq
                     	sudo apt clean
                      df -h
