name: Test1
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
   
    - name: S1
      run: |
       printf 'Free Disk Space: '
       df -h . | tail -1 | awk '{print $4}'
         
       sudo rm -rf /opt/ghc  						       || true
       sudo rm -rf /opt/hostedtoolcache                    || true
       sudo rm -rf /usr/share/dotnet                       || true
       sudo rm -rf /usr/share/swift                        || true
       sudo rm -rf /usr/local/graalvm/                     || true
       sudo rm -rf /usr/local/.ghcup/                      || true
       sudo rm -rf /usr/local/share/powershell             || true
       sudo rm -rf /usr/local/share/chromium               || true
       sudo rm -rf /usr/local/lib/node_modules             || true
       sudo rm -rf /usr/local/lib/android                  || true
       sudo rm -rf /usr/local/share/boost                  || true
       sudo rm -rf /home/runner/.cargo                     || true
       sudo rm -rf /home/runner/.rustup                    || true
       sudo rm -rf /usr/local/julia*                       || true
       sudo rm -rf /opt/microsoft                          || true
       sudo rm -rf /usr/lib/dotnet                         || true
       sudo rm -rf "$AGENT_TOOLSDIRECTORY"                 || true
       
       printf 'Free Disk Space: '
       df -h . | tail -1 | awk '{print $4}'


