name: Test
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
  
    - name: S1
      run: |
        du -sh /usr/local/.ghcup
        du -sh /opt/hostedtoolcache/CodeQL
        du -sh /usr/local/lib/android/sdk/ndk
        du -sh /usr/share/dotnet
        du -sh /opt/ghc
        du -sh /usr/local/share/boost
        
