name: Test
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
  
    - name: S1
      run: |
        dpkg-query -Wf '${Installed-Size}K\t${Package}\n' | sort -nr | head -10 | numfmt --from=auto --to=si

