name: Test1
on:
  workflow_dispatch:
jobs:
  bbbbbb:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [aarch64]
      fail-fast: false
      
    steps:
   
    - name: S1
      run: |
       printf 'Free Disk Space: '
       df -h . | tail -1 | awk '{print $4}'
         
       sudo rm -rf /opt/ghc > /dev/null 2>&1 &
       sudo rm -rf /opt/hostedtoolcache                   > /dev/null 2>&1 &
       sudo rm -rf /usr/share/dotnet                      > /dev/null 2>&1 &
       sudo rm -rf /usr/share/swift                       > /dev/null 2>&1 &
       sudo rm -rf /usr/local/graalvm/                    > /dev/null 2>&1 &
       sudo rm -rf /usr/local/.ghcup/                     > /dev/null 2>&1 &
       sudo rm -rf /usr/local/share/powershell            > /dev/null 2>&1 &
       sudo rm -rf /usr/local/share/chromium              > /dev/null 2>&1 &
       sudo rm -rf /usr/local/lib/node_modules            > /dev/null 2>&1 &
       sudo rm -rf /usr/local/lib/android                 > /dev/null 2>&1 &
       sudo rm -rf /usr/local/share/boost                 > /dev/null 2>&1 &
       sudo rm -rf /home/runner/.cargo                    > /dev/null 2>&1 &
       sudo rm -rf /home/runner/.rustup                   > /dev/null 2>&1 &
       sudo rm -rf /usr/local/julia*                      > /dev/null 2>&1 &
       sudo rm -rf /opt/microsoft                         > /dev/null 2>&1 &
       sudo rm -rf /usr/lib/dotnet                        > /dev/null 2>&1 &
       sudo rm -rf "$AGENT_TOOLSDIRECTORY"                > /dev/null 2>&1 &
       
       printf 'Free Disk Space: '
       df -h . | tail -1 | awk '{print $4}'

 
    - name: S1
      run: |
        for i in $(seq 1 100);
        do
            df -h . | tail -1 | awk '{print $4}' 
            sleep 1
        done


