name: XXXXX
on:
  workflow_dispatch:
jobs:
  build:
    name: ${{matrix.arch}}
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        include:
          - cpp_compiler: g++
            c_compiler: gcc,
          - cpp_compiler: g++-8
            c_compiler: gcc-8
          - cpp_compiler: clang++
            c_compiler: clang
    env:
      ALSULTAN_1: ${{matrix.cpp_compiler}}
      ALSULTAN_2: ${{matrix.c_compiler}}


    steps:
    
    - name: Source 
      run: |
        echo A=$ALSULTAN_1
        echo B=$ALSULTAN_2
