name: XXXXX
on:
  workflow_dispatch:
jobs:
  build:
    name: ${{matrix.NAME}}
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        include:
        
          - NAME: iOS
            PLATFORM: ios
            FRAMEWORK: ios
            PROFILE: NitaqPos,
            
          - NAME: MacOS
            PLATFORM: macos
            FRAMEWORK: maccatalyst
            PROFILE: NitaqPosMac,


    steps:
    
    - name: Source 
      run: |
        echo NAME=${{matrix.NAME}}
        echo PLATFORM=${{matrix.PLATFORM}}
        echo FRAMEWORK=${{matrix.FRAMEWORK}}
        echo PROFILE=${{matrix.PROFILE}}
